name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  IMAGE_NAME: gitlab-runner-machine-hetzner

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3

      - name: Identify version to build
        run: |
          egrep "^ARG DOCKER_MACHINE_DRIVER_HETZNER_VERSION=" Dockerfile | sed "s|^ARG ||" >> $GITHUB_ENV
          echo "GITLAB_RUNNER_VERSION=$(egrep "^FROM gitlab/gitlab-runner:" Dockerfile | awk '{print $2}' | cut -d: -f2 | cut -d@ -f1)" >> $GITHUB_ENV

      - name: Build image
        run: docker build . --file Dockerfile --tag "$IMAGE_NAME" --cache-from "ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest"

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Push image
        run: |
          IMAGE_ID="ghcr.io/${{ github.repository }}/$IMAGE_NAME"

          # Change all uppercase to lowercase
          IMAGE_ID="$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')"

          IMAGE_ID_VERSIONED="${IMAGE_ID}:${GITLAB_RUNNER_VERSION}-machine-hetzner-v${DOCKER_MACHINE_DRIVER_HETZNER_VERSION}"

          # Use Docker `latest` tag convention
          echo IMAGE_ID="$IMAGE_ID"
          echo IMAGE_ID_VERSIONED="$IMAGE_ID_VERSIONED"

          docker tag "$IMAGE_NAME" "$IMAGE_ID_VERSIONED"
          docker tag "$IMAGE_NAME" "$IMAGE_ID:latest"
          docker push "$IMAGE_ID_VERSIONED"
          docker push "$IMAGE_ID:latest"
