name: Docker build

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build image

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository for metadata
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Identify version to build
        id: version-meta
        run: |
          egrep "^ARG DOCKER_MACHINE_DRIVER_HETZNER_VERSION=" Dockerfile | sed "s|^ARG ||" | tee -a $GITHUB_OUTPUT
          echo "GITLAB_RUNNER_VERSION=$(egrep "^FROM gitlab/gitlab-runner:" Dockerfile | awk '{print $2}' | cut -d: -f2 | cut -d@ -f1)" | tee -a $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable=true
            type=raw,value=${{
              steps.version-meta.outputs.GITLAB_RUNNER_VERSION
            }}-machine-hetzner-v${{
              steps.version-meta.outputs.DOCKER_MACHINE_DRIVER_HETZNER_VERSION
            }},enable=true

      - name: Build Docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: ${{ steps.custom-meta.outputs.base-image-name }}:buildcache
        env:
          SOURCE_DATE_EPOCH: 0
